# Generated by Django 5.1.3 on 2025-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                    ('email', models.EmailField(max_length=191)),
                ('mode_of_study', models.CharField(max_length=100)),
                ('programme_applied', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('medium', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=100)),
                ('deb_id', models.CharField(max_length=100)),
                ('abc_id', models.CharField(max_length=100)),
                ('name_initial', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('aadhaar_no', models.CharField(max_length=12)),
                ('name_as_aadhaar', models.CharField(max_length=200)),
                ('parent_selected', models.BooleanField()),
                ('guardian_selected', models.BooleanField()),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_occupation', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('community', models.CharField(max_length=100)),
                ('mother_tongue', models.CharField(max_length=100)),
                ('differently_abled', models.CharField(max_length=100)),
                ('disability_type', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('access_internet', models.CharField(max_length=100)),
                ('comm_pincode', models.CharField(max_length=10)),
                ('comm_district', models.CharField(max_length=100)),
                ('comm_state', models.CharField(max_length=100)),
                ('comm_country', models.CharField(max_length=100)),
                ('comm_town', models.CharField(max_length=100)),
                ('comm_area', models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=100)),
                ('same_as_comm', models.BooleanField()),
                ('perm_pincode', models.CharField(max_length=10)),
                ('perm_district', models.CharField(max_length=100)),
                ('perm_state', models.CharField(max_length=100)),
                ('perm_country', models.CharField(max_length=100)),
                ('perm_town', models.CharField(max_length=100)),
                ('perm_area', models.CharField(choices=[('Rural', 'Rural'), ('Urban', 'Urban')], max_length=100)),
            ],
            options={
                'db_table': 'api_application',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                    ('email', models.EmailField(max_length=191)),
                ('name_initial', models.CharField(max_length=100)),
                ('qualifications', models.JSONField()),
                ('semester_marks', models.JSONField()),
                ('current_designation', models.CharField(max_length=255)),
                ('current_institute', models.CharField(max_length=255)),
                ('years_experience', models.IntegerField()),
                ('annual_income', models.IntegerField()),
            ],
            options={
                'db_table': 'api_studentdetails',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('email', models.EmailField(max_length=191, unique=True)),
                ('temp_register_no', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
