# Generated by Django 5.1.3 on 2025-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(max_length=191, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=191),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='email',
            field=models.EmailField(max_length=191),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(max_length=191, unique=True),
        ),
    ]
