# Generated by Django 5.2.7 on 2025-11-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_one', '0004_applicationstatus_auditlog_counsellor_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='setting_type',
            field=models.CharField(choices=[('admission', 'Admission Settings'), ('email', 'Email Settings'), ('payment', 'Payment Settings'), ('general', 'General Settings'), ('security', 'Security Settings'), ('system', 'System Settings'), ('guideline', 'Guidelines'), ('maintenance', 'Maintenance Settings')], max_length=50),
        ),
    ]
